import type { Project } from '@/content/types';

export type { Project, ProjectImage } from '@/content/types';

export const projects: Project[] = [
  {
    slug: 'project-one',
    index: '01',
    title: 'Project One',
    summary: 'Sixteen homes inside a frame that was already standing.',
    thumbnail: '/images/project-one-thumb.jpg',
    hero: '/images/project-one-hero.jpg',
    year: '2024',
    location: 'Nørrebro, Copenhagen',
    type: 'Housing · Retrofit',
    client: 'Nørrebro Boligforening',
    programme: 'Housing, workshops, shared kitchen',
    area: '3,400 m²',
    status: 'Built',
    body: [
      'A post-war housing block reworked from the inside out. Rather than demolish, we stripped the structure back to its frame, re-skinned it in a breathable envelope and returned the ground floor to the street as workshops and a shared kitchen.',
      'The result keeps every tonne of embodied carbon already standing on the site, and adds sixteen homes that read as though they had always been there.',
      'Residents stayed in place through two of the three construction phases. That constraint shaped more of the design than any drawing did — every detail had to be buildable one storey at a time, from the outside, without a crane on the street.',
    ],
    gallery: [
      { src: '/images/project-one-01.jpg', alt: 'An original window opening retained in the facade', span: 'half' },
      { src: '/images/project-one-02.jpg', alt: 'Brickwork of the retained structure', span: 'half' },
      { src: '/images/project-one-03.jpg', alt: 'Rendered volumes stepping down the slope', span: 'full' },
    ],
  },
  {
    slug: 'project-two',
    index: '02',
    title: 'Project Two',
    summary: 'Shade, water, and somewhere to sit — negotiated in the open.',
    thumbnail: '/images/project-two-thumb.jpg',
    hero: '/images/project-two-hero.jpg',
    year: '2023',
    location: 'Amager, Copenhagen',
    type: 'Public space',
    client: 'Københavns Kommune',
    programme: 'Civic square, water feature, planting',
    area: '6,100 m²',
    status: 'Built',
    body: [
      'A civic square built on the argument that shade, water and somewhere to sit are the three things a public space cannot do without. Everything else is negotiable, and was negotiated — in the open, over eleven months, with the people who use it.',
      'Materials were drawn from within fifty kilometres of the site. The paving is laid dry so it can be lifted, repaired and relaid without a single skip leaving the square.',
      'Forty-one trees were planted before any paving was set, so the canopy had two summers of growth before the square opened.',
    ],
    gallery: [
      { src: '/images/project-two-01.jpg', alt: 'Timber walkway running out to the pavilion', span: 'half' },
      { src: '/images/project-two-02.jpg', alt: 'Bridge structure seen from underneath', span: 'half' },
      { src: '/images/project-two-03.jpg', alt: 'The long pier reaching out over the water', span: 'full' },
    ],
  },
  {
    slug: 'project-three',
    index: '03',
    title: 'Project Three',
    summary: 'An acoustics brief that turned out to be about corridors.',
    thumbnail: '/images/project-three-thumb.jpg',
    hero: '/images/project-three-hero.jpg',
    year: '2023',
    location: 'Aarhus',
    type: 'Cultural',
    client: 'Aarhus Scenekunstcenter',
    programme: 'Rehearsal rooms, performance hall, offices',
    area: '4,800 m²',
    status: 'Built',
    body: [
      'A rehearsal and performance building for three resident companies who had never shared a roof. The brief was mostly a question of acoustics; the design turned out to be mostly a question of corridors, and who meets whom in them.',
      'A single top-lit spine runs the length of the plan. Every room opens onto it, so the building is legible from the moment you step inside.',
      'The three companies now programme a shared season. Nobody asked for that in the brief.',
    ],
    gallery: [
      { src: '/images/project-three-01.jpg', alt: 'Stone doorway in the existing elevation', span: 'half' },
      { src: '/images/project-three-02.jpg', alt: 'The street elevation, entrance beyond', span: 'half' },
      { src: '/images/project-three-03.jpg', alt: 'The city skyline after dark', span: 'full' },
    ],
  },
  {
    slug: 'project-four',
    index: '04',
    title: 'Project Four',
    summary: 'Twenty-two hectares planned as six neighbourhoods, not one.',
    thumbnail: '/images/project-four-thumb.jpg',
    hero: '/images/project-four-hero.jpg',
    year: '2022',
    location: 'Malmö',
    type: 'Masterplan',
    client: 'Malmö Stad',
    programme: 'Mixed-use masterplan, public realm',
    area: '22 ha',
    status: 'In delivery',
    body: [
      'Twenty-two hectares of former rail land, planned as six small neighbourhoods rather than one large one. Each has its own centre, its own mix of uses and its own way of meeting the water.',
      'The masterplan fixes very little: street widths, block depths, the position of the trees. Everything above ground level is left for the next forty years to decide.',
      'Three of the six neighbourhoods are now on site, each with a different architect. That was the point.',
    ],
    gallery: [
      { src: '/images/project-four-01.jpg', alt: 'The site and its waterfront, seen from the air', span: 'half' },
      { src: '/images/project-four-02.jpg', alt: 'A lit street between the first completed blocks', span: 'half' },
      { src: '/images/project-four-03.jpg', alt: 'The waterfront at night', span: 'full' },
    ],
  },
];
